import os
from pathlib import Path
import win32api
import shutil

home_dir = Path.home()  # The Home path of each OS which is universal
root_dir = home_dir / "Common Files"  # This is where all the files and dirs of this script will stay or be copied

# Ensure root directory exists
if not root_dir.exists():
    root_dir.mkdir(parents=True, exist_ok=True)

# Directories for different file types
directories = {
    ".pdf"  : root_dir / "PDFs",
    ".xls"  : root_dir / "ExcelFiles",
    ".xlsx" : root_dir / "ExcelFiles",
    ".ppt"  : root_dir / "PPTXFiles",
    ".pptx" : root_dir / "PPTXFiles",
    ".doc"  : root_dir / "WordFiles",
    ".docx" : root_dir / "WordFiles"
}

# Create the directories if they don't exist
for dir in directories.values():
    if not dir.exists():
        dir.mkdir(parents=True, exist_ok=True)

# Function to get all available drives
def get_drives():
    if os.name == 'nt':  # Windows-specific
        # Using win32api to get the available drives
        drives = win32api.GetLogicalDriveStrings().split('\000')[:-1]  # Exclude the empty string at the end
        return drives
    else:
        # For non-Windows systems (Linux/Mac), you can start from '/' or '/mnt' based on your system.
        return ['/']

# Function to handle file name conflicts by renaming
def get_unique_file_path(dest_dir, file_name):
    file_path = Path(file_name)  # Convert the string file_name to a Path object
    new_file_path = Path(dest_dir) / file_path.name  # Use file_path.name instead of file_name directly
    counter = 1
    while new_file_path.exists():
        # Rename file with a number if it already exists
        new_file_name = f"{file_path.stem}_{counter}{file_path.suffix}"  # Now using file_path.stem and file_path.suffix
        new_file_path = Path(dest_dir) / new_file_name  # Ensure the destination is a Path object
        counter += 1
    return new_file_path

# Function to skip system directories generated by CHATGPT 😅😅😅
def is_system_path(path):
    system_paths = [
        "C:\\Windows", 
        "C:\\Program Files", 
        "C:\\Program Files (x86)", 
        "C:\\Windows\\System32",
        "C:\\Users\\Public"
    ]
    # Check if the path starts with any of these system paths
    return any(str(path).startswith(system_path) for system_path in system_paths)

# Loop through all the drives
for drive in get_drives():
    root_path = Path(drive)  # Path for the root directory of each drive

    # Use os.walk() to manually walk through the directories and skip system paths
    for dirpath, dirnames, filenames in os.walk(root_path):
        try:
            # Skip system paths
            if is_system_path(Path(dirpath)):
                print(f"Skipping system path: {dirpath}")
                continue

            # Check the files in the directory
            for file_name in filenames:
                file = Path(dirpath) / file_name
                if file.suffix.lower() in directories:
                    dest_dir = directories[file.suffix.lower()]
                    dest_path = get_unique_file_path(dest_dir, file.name)

                    # Move the file to the destination directory
                    shutil.move(file, dest_path)
                    print(f"Moved {file} to {dest_path}")
        
        except (FileNotFoundError, PermissionError) as e:
            # Handle file not found or permission issues
            print(f"Error processing {dirpath}: {e}")
        except Exception as e:
            # Catch all other exceptions
            print(f"Unexpected error with {dirpath}: {e}")
